### ISSUE TITLE
Add -S for --smart-case

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#105]
I've always wanted a short version of `--smart-case`, and ripgrep uses `-S`, which is what I was leaning towards anyway, so let's do that.

**Comment by n1vux** [comment]
`-S` usage there is same as `ag` SilverSurfer usage, so that's good too.  
Glark, Kaki, Nak did not have a `-S` so no inconsistency.

**Comment by n1vux** [comment]
the data analysis for what flag options (and filetypes) `ag` and others have and we don't that was used above are logged on #99 .  (I didn't include `ripgrep` in that analysis as it wasn't on my horizon.)

This comment is just for xref.

**Comment by petdance** [comment]
Done.  d4d9a69
