### ISSUE TITLE
Look into making all options globals

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#11]
If we don't pass around the `$opt` hash, or don't need to, look into making all of the `$opt_X` variables package variables.  It will be safer because we can't mess up hash keys, and it will be faster.

**Comment by n1vux** [comment]
Alternatives would be encapsulating %opt with Mo[uo]se methods or a cheched-hash object.

**Comment by petdance** [comment]
> Alternatives would be encapsulating %opt with Mo[uo]se methods

Can't do that, because Ack needs to be stock Perl.

> If Package variables at global scope, consider making $opt_X into $Ack::Options::X

That might make sense.  Or just `$App::Ack::opt_x`.

**Comment by petdance** [comment]
See also #65

**Comment by petdance** [comment]
This has been done as much as is feasible.
