### ISSUE TITLE
Make all ack tests run with --noenv

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#124]
Tests like #123 seem to be passing for me and failing for others.  ack tests shouldn't be influenced by any ~/.ackrc files.

**Comment by n1vux** [comment]
with `prove`, ENV may be easier than commandline `--noenv`.  
Does the self-contradictory `ACK_OPTIONS=--noenv` error as absurd, or block `.ackrc` and the other ENVs ?  I'd suggest it *should* do the latter, and that could be helpful for this ?

**Comment by petdance** [comment]
ACK_OPTIONS has been removed as of 2.999_04.

**Comment by petdance** [comment]
This functionality is already in t/Util.pm in `build_ack_invocation`.
