### ISSUE TITLE
Consider removing the ACK_OPTIONS feature

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#129]
`ACK_OPTIONS` is analogous to `GREP_OPTIONS`, where you can pass commands in through an environment variable.

`GREP_OPTIONS` has been deprecated in GNU grep.  Can we get rid of `ACK_OPTIONS`, too?  Does anyone use it?  It causes security headaches.

**Comment by n1vux** [comment]
3.0 is certainly the ideal time to remove, if we're going to. 

Now that we have per-project .ackrc, `alias` should handle any reasonable usage that doesn't fit project .ackrc

Cookbook could include project .ackrc  as preferred substitute and/or `alias ack="$bin/ack --ackrc=mode7.ackrc"` as more detailed precise substitute for `export ACK_OPTIONS=....` in project default-shift scripting.

**Comment by rbowen** [comment]
No, I have never used that feature, and was, indeed, unaware of it.

**Comment by petdance** [comment]
And should we get rid of `ACKRC` while we're at it?

**Comment by n1vux** [comment]
re variable `ACKRC`, that may be required to test the test case being reported from some smoke sites. In which case it has some utility.  

Security implications are likely low, as if my malware can `setenv ACKRC` for user `root`  I don't need to do so in order to escalate privileges.

**Comment by petdance** [comment]
I'm not going to remove ACK_OPTIONS.  The code footprint is teeny, so it's not really a win other than eliminating a dozen lines of code in the entire tree.

**Comment by petdance** [comment]
I changed my mind.  I'm removing it.  7c2f864
