### ISSUE TITLE
ack.1 man page is no longer installed on Linux

### ISSUE THREAD

**Issue by shlomif** [beyondgrep/ack3#133]
The ack.1 man page is no longer installed on Linux. This is part of the Debian policy and is a good thing to have. I tried 2.999_02 from CPAN.

**Comment by petdance** [comment]
You’ll have to take it up with Debian. I don’t have anything to do with that.

**Comment by n1vux** [comment]
> s part of the Debian policy

What is Debian policy? To have or not have `man ack(1)`?
You said "from CPAN".
What does Debian policy even have to do with installed from CPAN?
Would your telegraphic report fairly translate as "CPAN install doesn't
install man files for use by man(1), and this could delay Debian packaging?"

If so, please indicate whether you did manual unzip&follow README steps,
CPAN(1), cpanm(1), or other utility; and whether this was as root/with sudo
or with auto wheel privileges or not.

Note that in 3Beta, final form of POD remix and split man/FAQ/cookbook has
not yet been finalized, so I am not surprised; your report may help as we
work towards that.

**Comment by shlomif** [comment]
On Sat, 13 Jan 2018 20:08:11 +0000 (UTC)
Bill Ricker <notifications@github.com> wrote:

> > s part of the Debian policy  
> 
> What is Debian policy? To have or not have `man ack(1)`?

See https://qa.debian.org/man-pages.html

> You said "from CPAN".
> What does Debian policy even have to do with installed from CPAN?
> Would your telegraphic report fairly translate as "CPAN install doesn't
> install man files for use by man(1), and this could delay Debian packaging?"

yes, there is /usr/bin/ack and yet /usr/share/man/man1/ack.1* is not present.

> 
> If so, please indicate whether you did manual unzip&follow README steps,
> CPAN(1), cpanm(1), or other utility; and whether this was as root/with sudo
> or with auto wheel privileges or not.
> 

I built the package as part of this mageia package - from the source tarball
downloaded from cpan: http://svnweb.mageia.org/packages/cauldron/ack/ .

> Note that in 3Beta, final form of POD remix and split man/FAQ/cookbook has
> not yet been finalized, so I am not surprised; your report may help as we
> work towards that.

Thanks!

> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Processing Tools - http://shlom.in/text-proc

Medusa’s gaze can turn people into stone. Buffy’s gaze can turn Medusa into
stone.
    — http://www.shlomifish.org/humour/bits/facts/Buffy/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by petdance** [comment]
I'm not clear what it is you're saying.  What needs to be done?

**Comment by shlomif** [comment]
On Sat, 13 Jan 2018 13:51:25 -0800
Andy Lester <notifications@github.com> wrote:

> I'm not clear what it is you're saying.  What needs to be done?
> 

Install a man.1.xz (or man.1 or similar) file in nroff format
under /usr/share/man/man1/ (or whatever the manpath is) so "man ack" and "man 1
ack" will work and document /usr/bin/ack :

shlomif@telaviv1:~$ man 1 ack
No manual entry for ack in section 1

Strangely enough "man ack" still works as does "man 3 ack" but maybe it is the
man command being clever here.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://is.gd/htwEXQ - Integrating GNU Guile into GNU coreutils

As to the Adjective: when in doubt, strike it out.
    — Mark Twain, “Pudd’nhead Wilson's Calendar”

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by petdance** [comment]
If you can look into this, it would be a big help.  I don't know why MakeMaker isn't using the contents of the EXE_FILE argument to build man pages from.

**Comment by shlomif** [comment]
On Sat, 13 Jan 2018 22:40:53 +0000 (UTC)
Andy Lester <notifications@github.com> wrote:

> If you can look into this, it would be a big help.  I don't know why
> MakeMaker isn't using the contents of the EXE_FILE argument to build man
> pages from.

No promises, but I'll try to help. Thanks!

> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Original Riddles - http://www.shlomifish.org/puzzles/

If a tree falls down in the middle of the forest, and there’s no one there to
hear it… what colour is the tree?
    — Monkey Island 2: LeChuck’s Revenge

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
I may have fixed it here - https://github.com/shlomif/ack3/tree/fix-issue-133 - ./ack did not have any POD.

**Comment by n1vux** [comment]
In Ack3, POD is in ack3 <https://github.com/beyondgrep/ack3>/lib
<https://github.com/beyondgrep/ack3/tree/dev/lib>/App
<https://github.com/beyondgrep/ack3/tree/dev/lib/App>/Ack
<https://github.com/beyondgrep/ack3/tree/dev/lib/App/Ack>/Docs/

It wouldn't be surprised if Makefile not changed yet to look there when
making ack.1 .
(Probably should make ackrc.5 also?)

Appending it back to `ack` is an answer, but is incompatible with splitting
into 3 PODs.

**Comment by karenetheridge** [comment]
I found this ticket while noticing that the manpages were missing in the `ack` executable in the latest dev release (2.999_03) -- are they installed anywhere now?  I have no `ack3` executable.

I would suggest putting pod back into `ack`, and possibly adding relevant pod into App::Ack as well. It would be very easy to do this in an automated fashion from a common source as part of the release prep process (yes I am volunteering to help).

**Comment by petdance** [comment]
The docs are moved to their own files now because it's more than just one page.  If you see a way to combine `lib/App/Ack/Docs/{Manual,FAQ,Cookbook}.pm` together, I'd love to hear it.

**Comment by karenetheridge** [comment]
perhaps in that case, the ack executable documentation can just point to the new location? That way the user knows where to look, rather than simply being faced with no docs at all (that he knows of).

**Comment by karenetheridge** [comment]
combining the pod together is also an option, if that would give a good user experience. pod mangling is fairly straightforward with Pod::Weaver.

**Comment by shlomif** [comment]
On Wed, 14 Mar 2018 13:36:37 -0700
Karen Etheridge <notifications@github.com> wrote:

> I found this ticket while noticing that the manpages were missing in the
> `ack` executable in the latest dev release (2.999_03) -- are they installed
> anywhere now?  I have no `ack3` executable.
> 
> I would suggest putting pod back into `ack`, and possibly adding relevant pod
> into App::Ack as well. It would be very easy to do this in an automated
> fashion from a common source as part of the release prep process (yes I am
> volunteering to help).
> 

thanks, Karen!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Buffy Factoids - http://www.shlomifish.org/humour/bits/facts/Buffy/

BYTE editors are men who seperate the wheat from the chaff, and then
carefully print the chaff.
-- based on Lionel Hummel (uiucdcs!hummel), derived from a quote by Adlai
Stevenson, Sr.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Any news? What do we do?

**Comment by petdance** [comment]
No news.  Not at the top of my list right now.

**Comment by petdance** [comment]
This should be fixed now.
