### ISSUE TITLE
feature request; search types

### ISSUE THREAD

**Issue by fizwit** [beyondgrep/ack3#141]
Search for a variable name on the left side of the equal sign (where it is defined)  (--def ?)

Search for a function name, and output the code for the function. (--func ?)

**Comment by n1vux** [comment]
if I haven't included in the Cookbook a how-to for approximating this already, we should. 
`-C7` or `-B1 -A10` combined with some context sensitivity in pattern gets close   
e.g. 
``` ack '\A\s*\K(\w+)(?=\s*=)' ~/bin/ ``` 
``` ack '\A\s*(?:sub|method)\s+\K(\w+)'  ~/bin/``` 
(where `\w+` looks for any (perlish)identifier can be replaced by desired search pattern, and should be wrapped in `(?:)` if it has an | in it )

**Comment by petdance** [comment]
Like @n1vux shows above, there are ways to get at this via regexes, but ack can't and won't try to understand languages in text files that it searches.
