### ISSUE TITLE
Search gzipped files

### ISSUE THREAD

**Issue by marcelpaulo** [beyondgrep/ack3#145]
I'm kind of new to ack, coming from ag, and I have a doubt. I searched attentively the issues here and `ack --man` but couldn't find an answer. I found this issue beyondgrep/ack2#566 but none here. Please forgive me if I overlooked something.

Is it possible to have ack search through gzipped files ?

**Comment by petdance** [comment]
No, I'm sorry, ack doesn't search gzipped files, and I don't have any plans for it to do so.  It's not something that could reasonably be done cross-platform.

**Comment by petdance** [comment]
If you're looking at different grepalike tools, you may find this chart helpful:

https://beyondgrep.com/feature-comparison/

**Comment by marcelpaulo** [comment]
Oh, this table is really useful, thanks for that !

**Comment by petdance** [comment]
You're welcome.  I'm glad it's useful.

**Comment by marcelpaulo** [comment]
I've just discovered that, once installed package `libtemplate-perl`, bash autocompletion can be generated running `make completion.bash`. A really good autocompletion it is, congratulations ! Perhaps it should be mentioned in that grepalike comparison chart. Autocompletion out-of-the-box like this eases the tool into one's fingertips.
