### ISSUE TITLE
--line doesn't work when in filter mode

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#146]
```
$ cat foo.txt | ack --line=92
ack: No regular expression found.
```

But it works if you use a filename:
```
ack --line=92 foo.txt
```

**Comment by petdance** [comment]
Same problem exists in ack2: https://github.com/beyondgrep/ack2/issues/668  I'm not concerned with backporting it unless it's trivial.

**Comment by n1vux** [comment]
Additional failure mode, quite hilarious

```
ack --lines=7
7:+++ exited with 0 +++
7:+++ exited with 0 +++
7:exit(0)                                 = ?
... repeating...
```

**Comment by petdance** [comment]
The `--lines` option has been removed.
