### ISSUE TITLE
`--and $pattern` to require non-ordered conjunction of RE matches  

### ISSUE THREAD

**Issue by n1vux** [beyondgrep/ack3#172]
In the Slack we've discussed `--and` a few times, and most recently it was favorable, but never opened a ticket, so here is one.

`--and $pattern` opens a can of semantics worms: it could mean any of

- in the same line (obvious meaning / likely intent usually)
- in the same file (possibly ditto with `-f` but files with `patA --and patB` in same line equally plausible)
- same paragraph #171 
- mutual -C12 context

**Comment by petdance** [comment]
I think we must have two `--and`s and `--or`s.  They might be `--andononesameline` and `--orononeline` and `--andinthesamefile` and `--orinthesamefile`.  Those names are horrible, of course, but they need to be explicit in how they're differnet.

Also, we can't combine any `--and` and `--or` options together. Also, we can't combine `ononeline` and `inthesamefile` options.  It will be a nightmare.

And if we open this can of worms, are we going to want `--not` versions of everything too?
