### ISSUE TITLE
It would be nice if ack had a more extensible architecture

### ISSUE THREAD

**Issue by singingfish** [beyondgrep/ack3#184]
I'm specifially thinking about being able to filter through PPI prior to search, but any static analysis type hooks would be good.  I did look at this but I couldn't work out how to achieve it.

**Comment by petdance** [comment]
Thanks for the feedback.

We thought extensibility would be good too, but ack is moving away from an extensible architecture.  ack2 had hooks for making your own plugins, but zero people ever made plugins for them, including me.  All that extensibility has been removed in ack3.

Elliott Shank did some stuff with a project called ppigrep long ago: https://metacpan.org/pod/distribution/PPIx-Grep/bin/ppigrep
