### ISSUE TITLE
Write a test that -g and -i and -I work together

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#196]
`-g` uses the rules for case checking.  This means it is affected by `-i`.  Make sure it is also respecting `-I`.

**Comment by Anders-E** [comment]
Where would you like this test implemented? I couldn't find any project/directory structure info so I was wondering if I should make a completely new test script or put it in an already existing one.

**Comment by petdance** [comment]
Thanks for looking into this.  `t/ack-g-i.t` would work.

**Comment by Anders-E** [comment]
Just noticed `-I` only overwrites `-i` if specified after `-i`.

This will be case-sensitive ...
```
ack -i -I
```
... while this won't:

```
ack -I -i
```

Just wanted to make sure this is intended behavior?

**Comment by petdance** [comment]
Yes, that's correct.  Because the `-i` might be in an .ackrc and you can then override it with `-I`.

**Comment by petdance** [comment]
I'm sorry that this ticket wasn't clear about what it is that I'm trying to test for.

The key here is that `-g` is a regex match on the files that it's searching for.  That means that `-i` will affect the matching.

`ack -g foo` should act exactly the same as `ack -f | ack foo`.  This means that the `-i` should affect the matching.

Say I have a file called `Changes`, like in the ~/ack3 directory.  If I do:

   $ ack -g changes
   $

I'm going to get nothing because `changes` doesn't match `Changes`.

But if I do it with the `-i` option:

    $ ack -i -g changes
    Changes
    $

I get the `Changes` because it's a case-insensitive match.

Conversely, if I have `-i` in my .ackrc file, I should be able to use `-I` on the command line to override the `-i` in my .ackrc file.

**Comment by Anders-E** [comment]
Isn't that what my tests do though?

`ack-g.t` already contains this check for '-i`:
```
subtest 'Case-insensitive via -i' => sub {
    plan tests => 1;
    my @expected = qw(
        t/swamp/pipe-stress-freaks.F
    );
    my $regex = 'PIPE';
    my @args  = ( '-i', '-g', $regex );
    my @files = qw( t/swamp );
    ack_sets_match( [ @args, @files ], \@expected, "Looking for -i -g $regex " );
};
```
So I added the complementary:
```
subtest 'Negate -i via -I' => sub {
    plan tests => 1;

    my @expected = qw();
    my $regex = 'PIPE';

    my @args = ( '-i', '-I', '-g', $regex);
    my @files = qw( t/swamp );

    ack_sets_match( [ @args, @files ], \@expected, "Looking for -i -I -g $regex" );
};
```

as well as the other test that checks basically the reverse.

**Comment by petdance** [comment]
> Isn't that what my tests do though?

Yes, they do.  I'm sorry, I misread the code..

**Comment by petdance** [comment]
Thanks for the code.  I love it when tickets can get closed.

**Comment by Anders-E** [comment]
No worries! Thank you for creating and maintaining this project!
