### ISSUE TITLE
t/invalid-ackrc.t may fail if custom PERLDOC formatters are active

### ISSUE THREAD

**Issue by eserte** [beyondgrep/ack3#202]
On some of my smokers the test suite fails:
```
    #   Failed test at t/invalid-ackrc.t line 81.
    #                   'NNAAMMEE
    #     ack - grep-like text finder'
    #     doesn't match '(?^ms:NAME.+ack(?:-standalone)?\s)'
    # Looks like you failed 1 test of 2.

#   Failed test 'Check --env --man'
#   at t/invalid-ackrc.t line 82.
# Looks like you failed 1 test of 3.
t/invalid-ackrc.t ............ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

Probably this happens if Pod::Perldoc::ToTextOverstrike is installed and a environment variable is set to use it `PERLDOC=-MPod::Perldoc::ToTextOverstrike`

**Comment by petdance** [comment]
Interesting.  I may just have to bypass all that top-of-the-file checking.

**Comment by petdance** [comment]
I didn't even know about Pod::Perldoc::ToTextOverstrike and now I'm using it because I like the colors much more. 👍

**Comment by petdance** [comment]
Fixed, thanks.  cf0ab1c
