### ISSUE TITLE
Incorrect regex handling causing unmatched error

### ISSUE THREAD

**Issue by vit9696** [beyondgrep/ack3#205]
Sample example triggering the issue:

```
$ ack -s --type-set='all:match:.*' -k value /directory/ --output=l
/directory/file
Unmatched [ in regex; marked by <-- HERE in m/\$([ <-- HERE ])/ at /opt/local/bin/ack line 845, <__ANONIO__> line 718.
```

I am quite unfamiliar with the code, but I think the usage needs to be guarded with an empty check, potentially replacing

```perl
$output =~ s/\$([$special_vars_used_by_opt_output])/$keep{$1}/ego;
```

with

```perl
if (scalar @special_vars_used_by_opt_output != 0) {
    $output =~ s/\$([$special_vars_used_by_opt_output])/$keep{$1}/ego;
}
```

**Comment by petdance** [comment]
I've reduced the problem here and have made a new ticket over at #206.

What is it you're trying to achieve here?  What led you to make an `--all` type?  Why the `-k`?  I think you might be over-complicating things.

**Comment by vit9696** [comment]
@petdance thanks for your help =)

This line is part of a fairly old script I use to find matches in any files in a directory with basic regex support and hex escaping. I think -k and --type were working around some issue in ack related specifically to binary files. Output is here to hide the "garbage", since I only need to see whether the file matches or not. The full function looks as follows, and while I believe it can certainly be optimised to some level, I have never looked at it at a better detail.

```
function ackw() {
  if [ "$#" -ne 2 ]; then
    echo 'Usage: ackw <pattern> <dir>'
    return -1
  fi
  ack -s --type-set='all:match:.*' -k "$1" "$2" --output=ackwline | sed 's/:[0-9]*:ackwline$//' | uniq
}
```

**Comment by petdance** [comment]
If all you want is a list of files that matches the pattern, you use the `-l` flag.

    ack -l pattern

That will give you a list of all the files that it matches.


```
function ackw() {
  if [ "$#" -ne 2 ]; then
    echo 'Usage: ackw <pattern> <dir>'
    return -1
  fi
  ack -l "$1" "$2"
}
```

Also, the `--type-set` isn't doing anything, because there's not a corresponding use of `--all`.

If you're wanting to search binary files as well, then you're probably better off using `grep`.

    grep -l -R "$1" "$2"

**Comment by vit9696** [comment]
The biggest advantage of using ack was its speed, and I think there was some limitation on grep with regexes as I use BSD grep and not GNU.

Thanks for pointing out `-l` flag. It could be that this flag is either relatively new, or I failed to find it in the manual. I simplified the function to `ack -l --type-set='all:match:.*' -k "$1" "$2"`.

The claim that `--type-set` is not doing anything is incorrect. Although I believe it could be some of my understanding, I get the following results, and they back my claim regarding the use of `-k` and `--type-set='all:match:.*'` together:

```
$ ack -l --type-set='all:match:.*' -k "\xCA\xFE\xBA\xBE" /System/Library/Extensions
/System/Library/Extensions/AppleIntelHD4000GraphicsMTLDriver.bundle/Contents/MacOS/libigdmd.dylib
<many entries>
$ ack -l -k "\xCA\xFE\xBA\xBE" /System/Library/Extensions
<nothing>
$ ack -l "\xCA\xFE\xBA\xBE" /System/Library/Extensions
<nothing>
```

**Comment by petdance** [comment]
Aha, you're right.  The `-k` says to only search for types it knows about.

> The biggest advantage of using ack was its speed, 

For what you're doing, ack is not going to be faster than grep, guaranteed.

This works just find for me on my Mac:

    grep -l -R "\xCA\xFE\xBA\xBE" /System/Library/Extensions

**Comment by vit9696** [comment]
You will be surprised, but the speed difference is quite noticeable. I tried searching the whole /System folder for `"\xCA\xFE\xBA\xBE"` and for me `ack` took 1 minute 34 seconds, and `grep` needed 4 minutes 31 seconds with basic `date` measurement. Since I in fact ran `grep` after `ack`, its time was likely even better than usual due to caching. With the need to frequently search for large amounts of files, like several macOS filesystem dumps, a tool that searches more than twice slower is kind of unproductive.

The example with regexes I gave above was slightly incorrect, and it actually should be `"\xCA?\xBA\xBE"`. However, this makes things even slower, and I remember quite well that `grep -E` had some weird limitations in its regex engine on BSD systems.

Given that the more descriptive bugreport is now in a separate issue, should I close this one?

**Comment by petdance** [comment]
Well, this is astonishing to me.

```
[10:57:21] SVN alester-3:~ $ time ack -l --type-set='all:match:.*' -k "\xCA\xFE\xBA\xBE" /System/Library/Extensions | sort > fooack.txt

real	0m6.429s
user	0m2.426s
sys	0m1.056s
[10:57:42] SVN alester-3:~ $ time grep -l -R "\xCA\xFE\xBA\xBE" /System/Library/Extensions | sort > foogrep.txt

real	0m9.523s
user	0m8.611s
sys	0m0.417s
[10:57:56] SVN alester-3:~ $ diff fooack.txt foogrep.txt
[10:58:06] SVN alester-3:~ $
[10:58:35] SVN alester-3:~ $ wc -l fooack.txt
      83 fooack.txt
```

I'd have to guess that grep is doing something not very optimal on dealing with binary files.
