### ISSUE TITLE
Unknown option: range-stop

### ISSUE THREAD

**Issue by ohmycloud** [beyondgrep/ack3#228]
There are a few typos in the following section:

[MATCHING-IN-A-RANGE-OF-LINES](https://beyondgrep.com/documentation/ack-v3.1.0-man.html#MATCHING-IN-A-RANGE-OF-LINES)

```shell
ack --range-start='^sub \w+' --range-stop='^}' print data/testfile
```

it says that:

```
Unknown option: range-stop
ack: Invalid option on command line
```

it should be `--range-end` however.

**Comment by petdance** [comment]
Oops, thanks for catching that.  Committed in ac72598.
