### ISSUE TITLE
Latest version of ack on chocolatey is 2.22

### ISSUE THREAD

**Issue by digeomel** [beyondgrep/ack3#236]
I just tried to upgrade my local ack on Windows with chocolatey and it seems it still offers version 2.22 as the latest:

https://chocolatey.org/packages/ack

**Comment by petdance** [comment]
The ack project itself doesn't have anything to do with the packaging of ack for the various package systems.

On the page you linked, I see two maintainers in the left sidebar.  I believe that they are github users @alanstevens and @tylerszabo.  Maybe they'll have some input they can add to this ticket.

**Comment by n1vux** [comment]
Meantime, since Ack is a pure-perl module (not using any C-header libraries), Chocolatey/Strawberry users can download the File::Next and App::Ack modules directly from CPAN, evading the Chocolatey package manager.

**Comment by digeomel** [comment]
@n1vux I tried with Perl too, as written in the readme. This is what I get:

```
λ perl -MCPAN -e install File::Next
Can't locate CPAN/Author.pm in @INC (you may need to install the CPAN::Author module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/core_perl/CPAN.pm line 19.
BEGIN failed--compilation aborted at /usr/share/perl5/core_perl/CPAN.pm line 19.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

So I assume I need to install the Author module too and possibly other dependencies? I am not a Perl expert so any help is appreciated.

Perl version seems to be according to requirements:

```
λ perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi
```

**Comment by petdance** [comment]
It looks like your local CPAN module isn't set up, but I've never seen that error before.  It's something having to do with CPAN.pm, not File::Next.

You can bypass all of that and just download `ack` as a single script.  See "Install the executable" at https://beyondgrep.com/install/

**Comment by digeomel** [comment]
Indeed, that worked like a charm, thank you! 😊👍
It would still be nice if chocolatey updated their version, although I fully agree it's not your responsibility.
I think my problems stem from the fact that I probably installed ack through chocolatey initially, and that installed Strawberry Perl as a dependency, which doesn't seem to be completely fullproof, not on my setup at least.

**Comment by tylerszabo** [comment]
I'll make a priority to publish the updated version. I was going to set up automated packaging, first, but I can do another manual update to speed up the release.

**Comment by tylerszabo** [comment]
Looks like it's approved and getting installed (https://chocolatey.org/packages/ack/3.1.1).

**Comment by petdance** [comment]
Please let me know when it's out there so I can tweet that it's out there for Windows folks to use.

**Comment by tylerszabo** [comment]
That's what I mean - it's out there and people are getting it when they install Ack on Chocolatey :)
