### ISSUE TITLE
Revisit mutex options

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#25]
There are a lot of options that should probably be mutexed.

**Comment by n1vux** [comment]
iirc the reason we didn't MUTEX but just silently took last version is having ~/.ackrc ./.ackrc ENVIRONMENT and commandline versions in a hierarchy.  

We'd need to make the options warn/error only if the inconsistency is in the same source. If we can make / find a Getopt validation extension that can do that generically ... don't want to recode it once for each mutex set.

**Comment by petdance** [comment]
We already do a lot of mutex stuff.  It's not just about .ackrc/env, but about asking for arguments that don't make sense together.  `-f` and `-C`, for example.

**Comment by petdance** [comment]
Underline must be mutex with, off the top of my head, --output, -f, -g.

**Comment by petdance** [comment]
`-f` and `-v` must be mutex.  `-g` and `-v` should be fine.

**Comment by petdance** [comment]
Related tickets; #159, #158, #144, #66, #57.  These must all be done as part of this ticket.  I wish GitHub had ticket dependencies.

**Comment by petdance** [comment]
Updated: cb1acae

**Comment by petdance** [comment]
Done 2e1090ca0f50d6cdfa82a5a5f945f63d4e7e3958
