### ISSUE TITLE
Add -t as alias for --type, -T for --type=no-

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#277]

**Comment by petdance** [comment]
This should include an announcement that --type and --notype will go away in ack4.

**Comment by n1vux** [comment]
Why not allow both `-t` and `--type` in ack4 ? 
Supporting both classic Bell syntax and Gnuish verbosity supports choice.

**Comment by petdance** [comment]
`--type=perl` will still be around.  `--perl` will not.

**Comment by petdance** [comment]
Done. f1cf364e32c5f1b688b50377e4a201b6271b2423
