### ISSUE TITLE
Make a new "Actions:" section in --help

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#280]
There are some options that change how ack works: -c, -l, -L, -f and -g.  Move these options into an "Actions:" group in the top of help.

**Comment by hftf** [comment]
For convenience, a possibly related list of options may be found here: https://github.com/beyondgrep/ack3/issues/157#issuecomment-428813738

**Comment by petdance** [comment]
Thanks for this, @hftf , I'd forgotten I made that list.  They're not all actions in the sense that I meant, but certainly `--dump` and `--help-types` and `--create-ackrc` are actions that should be mutex from the others.

**Comment by petdance** [comment]
Done: 5f59972
