### ISSUE TITLE
Should filenames be colored when using -c (--count)?

### ISSUE THREAD

**Issue by hftf** [beyondgrep/ack3#282]
See title. I was expecting the filenames to be colored in the last two outputs.

> <img width="351" alt="ack-color" src="https://user-images.githubusercontent.com/312957/68523781-dc6c0d80-028b-11ea-9099-c788521df75c.png">

Are there any other features currently in the same boat?

Version: ack v3.2.0

See also: #61, https://github.com/beyondgrep/ack2/issues/568

**Comment by petdance** [comment]
Would that be helpful if it was?

**Comment by hftf** [comment]
Yes, it would be very helpful so I can easily distinguish the counts from the many long filenames of varying lengths usually containing numbers.

**Comment by petdance** [comment]
OK, let's add it.

Do you know Perl?  Would you like to take a stab at making the change?  I've got a bunch of other things I'm working on right now so can't.

**Comment by hftf** [comment]
I don’t know Perl, but I could probably pick it up. I could take a stab later this winter – I'm also very busy, so no guarantees though (and no need to assign officially to me).

**Comment by matthewhughes934** [comment]
Is this still desired? If so, I'd be happy to give it a shot.

**Comment by petdance** [comment]
Yes, it still seems like something worth doing. Thanks for the offer.

We will need tests updated to verify the behavior, too.

Like all the other coloring, it should default to on, unless the output is being redirected, in which case it should default to off.

**Comment by petdance** [comment]
This has been completed.  Thanks.
