### ISSUE TITLE
Can't locate object method "getoptionsfromarray" via package "Getopt::Long::Parser" 

### ISSUE THREAD

**Issue by sdm7g** [beyondgrep/ack3#287]
single file version of Ack v3.2.0 gives error:

`Can't locate object method "getoptionsfromarray" via package "Getopt::Long::Parser" at ./bin/ack3 line 4192. `

where: `perldoc -m Getopt::Long | grep '$VERSION' `  =>  2.38 

I see from issue 143 in ack2 and from current sources that a check for 2.38 was added back in v2, however it looks like Makefile.PL specifies  2.39 , so maybe that version number needs to be bumped up for single file version of ack3.

**Comment by sappjw** [comment]
Updating Getopt::Long on my system does seem to fix the problem.

**Comment by petdance** [comment]
I'll add a version requirement so that at least it tells you the real problem.

**Comment by petdance** [comment]
It looks like the minimum Getopt::Long for `getoptionsfromarray` is 2.39, not 2.38.

**Comment by petdance** [comment]
This will be in the next release.
