### ISSUE TITLE
Make regex errors easier to understand

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#290]
The regex errors ack gives are pretty hard to read.

```
$ ack 'foo(bar'
ack: Invalid regex '(?i)foo(bar':
  Unmatched ( in regex; marked by <-- HERE in m/(?i)foo( <-- HERE bar/ at /Users/andy/bin/ack line 579
```

Problem #1 is that there's that `(?i)` which is there because I have smartcase on but really is not part of the pattern that the user put in.  So, we should do a regex test before doing adding any `/i` or `(?i)` or whatever.

We also unnecessarily list the filename which helps the user not at all.

Finally, I think that whole `<-- HERE` thing is pretty tough to read.

I suggest we have this:

```
$ ack 'foo(bar'
ack: Invalid regex 'foo(bar':
Regex: foo(bar
          ^---HERE Unmatched ( in regex
```

Thoughts?  I've started this on a branch called `regex-diag`.

**Comment by n1vux** [comment]
(Pleasantly surprised I could effectively view branch compare on small tablet.)
If that's all it takes to make a better, user-centric  error diagnostic, 
It is a very good thing.

(It will be interesting how the tests for this behave over a wide range of Perl versions, but if there is some variation, we can probably deal with that too.)

**Comment by petdance** [comment]
Committed to dev at c1fc9f0.
