### ISSUE TITLE
The line number separator should be the same for context and --passthru

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#291]
```
$ ack foo -C
t/text/raven.txt
91-
92-Then, methought, the air grew denser, perfumed from an unseen censer
93:Swung by seraphim whose foot-falls tinkled on the tufted floor.
94-"Wretch," I cried, "thy God hath lent thee -- by these angels he hath sent thee
95-Respite-respite and nepenthe from thy memories of Lenore!"
```

The line number is followed by a colon on the matching line (93) and by a hyphen on the non-matching context lines (91, 92, 94, 95).  This matches grep's behavior.

However, with `--passthru`, it's always colon, even on non-matching lines.  The non-matching lines for passthru should be the same as non-matching lines for context.

**Comment by petdance** [comment]
Done. 7100141

**Comment by n1vux** [comment]
Is changing this behavio[u]r in 3.3 breaking an interface that should be deferred to 4.0?

I ask this thinking that a pipeline using `ack --passthru` might be relying upon current behavior.
(While I tend to only use *--passthru*  with arguments that don't create line numbers, someone else might be getting numbers and relying upon the `name:99:line` or `99:line` standard that `-C7` (reasonably) departs from.)

*If* we include this in 3.n, it needs to be highlighted in release notes as a non-compatible change for complex pipelines. 

(I am not arguing against making `--passthru` consistent with `-Cn` just how to minimize disruption.)

**Comment by petdance** [comment]
I'm not worried about it.  It's in the change log and I bet that nobody uses --passthru with line numbers anyway.
