### ISSUE TITLE
Doc bug re: --range-end

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#308]
after  and end are not working together here as suggested

     Or to search after Perl's `__DATA__` or `__END__` markers, you would do

          ack pattern --range-end='^__(END|DATA)__'

**Comment by epement-db** [comment]
This correction will fix the documentation error. Suggested fix:

```
 Or to search after Perl's `__DATA__` or `__END__` markers, you would do

      ack pattern --range-start='^__(END|DATA)__'
```

**Comment by petdance** [comment]
Thanks, this has been fixed.
