### ISSUE TITLE
suggestion: automatically ignore tags file

### ISSUE THREAD

**Issue by halfmanhalffish** [beyondgrep/ack3#313]
ctags produces a file named 'tags' and I think it would be helpful if Ack ignored it, at least by default. It duplicates function names and variable names taken from source files.

**Comment by petdance** [comment]
Thanks for the suggestion.  I use tags, too, and I've pondered this myself over the years, but I think that it's not something that's universal.  Sometimes people have it as `tags` and sometimes it's `Tags` and I just think it's too fraught with potential nasty surprises.  My suggestion is to have a `--ignore-file=is:tags` in your ~/.ackrc file, or even better in the project's .ackrc file.
