### ISSUE TITLE
| ack -v

### ISSUE THREAD

**Issue by halfmanhalffish** [beyondgrep/ack3#315]
Is there a way to exclude lines based on a negative search, without losing styling?

In the old days of find | xargs grep I often used to add a grep -v onto the end, but if I do
ack sthg | ack -v sthelse
then I lose colours and newline breaks.

ack sthg -v somethingelse
doesn't work

**Comment by petdance** [comment]
`ack` does not colorize its output if that output is being piped.  You could force it on with `ack this --color | ack -v that`.

**Comment by halfmanhalffish** [comment]
Thanks.
