### ISSUE TITLE
ack shows results from the .vscode/ directory (using ack v3.4.0)

### ISSUE THREAD

**Issue by szabgab** [beyondgrep/ack3#324]
Probably ack should skip the .vscode directory by default

In any case I added

```
--ignore-dir=.vscode
```

to the ~/.ackrc file to avoid this.

**Comment by petdance** [comment]
Sounds good.  Is there anywhere that documents this?

**Comment by szabgab** [comment]
It is mentioned on this page: https://code.visualstudio.com/docs/getstarted/settings

**Comment by petdance** [comment]
Thanks for this.  Anything else in VS Code that we should be ignoring?

**Comment by szabgab** [comment]
I am not an expert on VS Code, this is the only one I encountered so far.

**Comment by petdance** [comment]
This has been changed and will go out in v3.6.0
