### ISSUE TITLE
Support bazel file types

### ISSUE THREAD

**Issue by eveecus** [beyondgrep/ack3#327]
Bazel is an open-source build and test system developed by Google.
* Main page https://bazel.build/
* Companies using bazel: https://bazel.build/#trusted-by-industry-leaders

I created a $HOME/.ackrc with a few bazel extensions about 6 months ago and it has been working well for me.

My .ackrc looks something like this:
```
# $HOME/.ackrc 
# Bazel
# https://docs.bazel.build/versions/master/skylark/bzl-style.html
--type-add=bazel:ext:bzl
# https://docs.bazel.build/versions/master/guide.html#bazelrc-the-bazel-configuration-file
--type-add=bazel:ext:bazelrc
# https://docs.bazel.build/versions/master/build-ref.html#BUILD_files
--type-add=bazel:is:BUILD
# https://docs.bazel.build/versions/master/build-ref.html#workspace
--type-add=bazel:is:WORKSPACE
```

**Comment by petdance** [comment]
This has been added in 58c2e5e.  Thanks.
