### ISSUE TITLE
Unable to ignore tags from results

### ISSUE THREAD

**Issue by btoone** [beyondgrep/ack3#331]
I just installed ack3 via homebrew, did my first search and the results included content from "tags". I read through the many issues discussing this and added a `.ackrc` to my home dir with the `--ignore-file=is:tags`. 

However searching still shows content from tags. I assume the problem is with my system since this solution is used by the project itself but I don't know how else to debug my problem.

I tried adding a project level `.ackrc` but the results are the same.

I also add `--ignore-file=is:schema.rb` to the project `.ackrc` to see if I could ignore a file that IS showing up in the results. After re-running the search the `schema.rb` results no longer showed up in the results, so the config is being used. 

Suggestions?

```
✖ which ack
/usr/local/bin/ack

✖ ack --version
ack v3.4.0 (standalone version)
Running under Perl v5.32.0 at /usr/local/opt/perl/bin/perl
```

In my `.ackrc`
```
✖ cat ~/.ackrc
--ignore-file=ext:log
--ignore-file=is:tags
```

Results of dump
```
✖ ack --dump | ack ignore-file
  --ignore-file=ext:bak
  --ignore-file=ext:gif,jpg,jpeg,png
  --ignore-file=ext:gz,tar,tgz,zip
  --ignore-file=ext:mo
  --ignore-file=ext:pdf
  --ignore-file=ext:pyc,pyd,pyo
  --ignore-file=ext:so
  --ignore-file=is:.DS_Store
  --ignore-file=is:.git
  --ignore-file=match:/[.-]min[.]js$/
  --ignore-file=match:/[.]css[.]map$/
  --ignore-file=match:/[.]css[.]min$/
  --ignore-file=match:/[.]js[.]map$/
  --ignore-file=match:/[.]js[.]min$/
  --ignore-file=match:/[.]min[.]css$/
  --ignore-file=match:/[._].*[.]swp$/
  --ignore-file=match:/^#.+#$/
  --ignore-file=match:/core[.]\d+$/
  --ignore-file=match:/~$/
  --ignore-file=ext:log
  --ignore-file=is:tags
```

Results of search
```
✖ ack tone_analyzer_results *
db/schema.rb
343:  create_table "tone_analyzer_results", force: :cascade do |t|

db/migrate/20190404224809_create_tone_analyzer_results.rb
3:    create_table :tone_analyzer_results do |t|

tags
122:CreateToneAnalyzerResults	db/migrate/20190404224809_create_tone_analyzer_results.rb	/^class CreateToneAnalyzerResults < ActiveRecord::Migration[5.2]$/;"	c
486:change	db/migrate/20190404224809_create_tone_analyzer_results.rb	/^  def change$/;"	f	class:CreateToneAnalyzerResults
```

Tag file in question
```
✖ ls -al tags
-rw-------  1 brandon  staff  803796 Jan 23 08:49 tags
```

Results of search after adding a project level `.ackrc` file and testing a filter to ignore results from `schema.rb` file.
```
✖ cat .ackrc
--ignore-file=is:schema.rb
--ignore-file=is:tags

✖ ack --dump | ack ignore-file=is
  --ignore-file=is:.DS_Store
  --ignore-file=is:.git
  --ignore-file=is:tags
  --ignore-file=is:schema.rb
  --ignore-file=is:tags

✖ ack tone_analyzer_results *
db/migrate/20190404224809_create_tone_analyzer_results.rb
3:    create_table :tone_analyzer_results do |t|

tags
122:CreateToneAnalyzerResults	db/migrate/20190404224809_create_tone_analyzer_results.rb	/^class CreateToneAnalyzerResults < ActiveRecord::Migration[5.2]$/;"	c
486:change	db/migrate/20190404224809_create_tone_analyzer_results.rb	/^  def change$/;"	f	class:CreateToneAnalyzerResults
```

**Comment by btoone** [comment]
Update: Details from some more investigation. 

* Results are also showing up when my pattern matches in `node_modules/*`
* In another project, results that are verified to be in the `tags` file, are not returned in the results (working as expected in this other project).

Given this, it seems there is something weird either on my system or in the particular project root causing Ack to not ignore the normal paths/files. 

I would still be interested if anyone could help me debug this further but I think we can close this issue as the problem appears to be really specific to my environment.

**Comment by petdance** [comment]
Did you figure anything out?

**Comment by btoone** [comment]
Nope, just what I have updated this issue with. My particular project seems to be the issue. Any debugging tips?

**Comment by petdance** [comment]
Hold on, I just noticed the problem.

    ack tone_analyzer_results *

That `*` is specifying files and directories to read.  When you specify a filename or directory name, it bypasses all the rules.  ack assumes that if you specify a filename, then you know what you are doing and want to search that exact file.

Don't specify the `*`.

**Comment by btoone** [comment]
Smh. Thank you and so sorry I didn't realize that earlier. Retested and it works as expected.

**Comment by petdance** [comment]
It's a common mistake.  If I had a way of detecting that someone did `ack whatever *` I would throw a warning, but of course I can't because the shell globs it out before ack can see.
