### ISSUE TITLE
Launching command from Java but exit code is 1

### ISSUE THREAD

**Issue by DevelopEngynya** [beyondgrep/ack3#338]
Hello,
I need to run the "ack" command directly from a Java program, it just doesn't work and returns exit code = 1.
If I run the same shell command, it works fine.

- I have Mac 10.15.7 Catalina
- I installed ack via home brew
- I also tried including the command in an external bash script and running that script from Java.

Thanks for any form of help

**Comment by petdance** [comment]
I just responded on the ack-users list.  We can diagnose either here or there.

Can you see any of the output from ack when you run it in Eclipse?  Do you get an error message?  Can you run other things than ack from inside Eclipse?  

My first thought, without knowing anything else, is that somehow you have your PATH different between Eclipse and your shell.  Or, it could be PERL5LIB, and ack can’t find the standard libraries.

We need more details about the “something goes wrong”.  It doesn’t sound like you’re doing anything weird.

What if you just run “ack -h”, where it doesn’t do anything but show a help screen?

I think if we can get some more details, we’ll get this figured out.
