### ISSUE TITLE
How to install ack on WSL?

### ISSUE THREAD

**Issue by mameen** [beyondgrep/ack3#344]
Hi is Windows Subsystem for Linux supported? how to install on WSL?

**Comment by petdance** [comment]
I'm sorry, I don't have specific instructions, and I don't know anything about Windows.  If you can run Perl, then you can install ack.  Do you have Perl on WSL?  If you have Perl, you should be able to run it.

What is your setup like?  Do you have Perl?  If you run `perl -v`, what does it show you?

**Comment by mameen** [comment]
Thanks, Andy, for replying. 

I do have perl in my `WSL`
```
perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)
```

my WSL2 installation
```
wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         2
```

Since my XSL is based on ubuntu, I tried the ubuntu command 

```
$ sudo apt-get install ack-grep

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ack-grep
```

**Comment by petdance** [comment]
I suspect you can install modules using the `cpan` program.  You should just be able to run

    cpan install App::Ack

How does that work for you?

**Comment by mameen** [comment]
```
Running make for P/PE/PETDANCE/File-Next-1.18.tar.gz
  PETDANCE/File-Next-1.18.tar.gz
  make -- NOT OK
  No such file or directory
  PETDANCE/ack-v3.5.0.tar.gz
  Has already been unwrapped into directory /home/####/.cpan/build/ack-v3.5.0-2
  PETDANCE/ack-v3.5.0.tar.gz
  Has already been prepared
Running make for P/PE/PETDANCE/ack-v3.5.0.tar.gz
Warning: Prerequisite 'File::Next => 1.18' for 'PETDANCE/ack-v3.5.0.tar.gz' failed when processing 'PETDANCE/File-Next-1.18.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  PETDANCE/ack-v3.5.0.tar.gz
  make -- NOT OK
  No such file or directory
```

then.. when I try to run it I get
```
:~/.cpan$ ./build/ack-v3.5.0-0/ack
Can't locate File/Next.pm in @INC (you may need to install the File::Next module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./build/ack-v3.5.0-0/ack line 11.
BEGIN failed--compilation aborted at ./build/ack-v3.5.0-0/ack line 11.
```

**Comment by petdance** [comment]
You don't have the program `make` on your system. I guess that doesn't come with WSL. If you can get `make`, then go ahead and install that.

The alternative is to just download the all-in-one ack program from here: https://beyondgrep.com/install/

That has a link to `https://beyondgrep.com/ack-v3.5.0`. (It will change over time)  Download that program to your machine and you can run it.

Now, I don't know how to make that download run on Windows, or where you have to put it. At the very least you should be able to do `perl ack ....`

**Comment by mameen** [comment]
The binary worked. Thanks!

**Comment by petdance** [comment]
You're welcome.

To be clear, it's not a binary. It's still a Perl script, just all in one text file.
