### ISSUE TITLE
$ not escaped by \Q?

### ISSUE THREAD

**Issue by uberbrodt** [beyondgrep/ack3#353]
Hi, I'm seeing a strange behaviour when I'm searching a directory for files with `$cluster` in them.

this returns...a lot of stuff that's not relevant:
```ack -Q "$cluster" /my-folder```

However, this returns what I want:
```ack -Q "\$cluster" /my-folder```

I thought that `-Q` would escape `$`? But perhaps not?

Versions:
```
$  ack --version
ack v3.5.0 (standalone version)
Running under Perl v5.30.2 at /usr/bin/perl
```

on Mac OSX Big Sur 11.6.3

**Comment by petdance** [comment]
`$cluster` is being interpolated as a shell variable.

"Double quotes" allow interpolation of shell variables, and 'single quotes' do not.

Try this to see the difference.

    echo "$PATH"
    echo '$PATH'

**Comment by petdance** [comment]
This is why I always use 'single quotes' if I have to ack for anything that requires quoting. Even if there's not a `$` in the search string, it's just habit.  There are other shell characters that can cause problems as well, like `!`.  Try:

    echo '!'
    echo "!"

The latter one should complain "!: event not found".

**Comment by n1vux** [comment]
About the only time to use double quotes with an Ack pattern is when having defined a reusable pattern as a Shell variable that then needs interpolation into larger patterns, as
```bash
v='[aeiouy]'  # Vowels
ack -i "\bsm${v}th${v}*\b" names.lst  # search for smith smythe smithie and stranger variants 
```
(This can be tricky because need to know which `\n` escapes are known to shell and thus require quoting as `\\n`)

**Comment by uberbrodt** [comment]
Yes, you're all right. Don't know why that escaped my mind this morning.
Thanks!

**Comment by petdance** [comment]
> Don't know why that escaped my mind this morning.

Because you're human. :-)
