### ISSUE TITLE
beyondgrep.com SSL certificate expired

### ISSUE THREAD

**Issue by ketch** [beyondgrep/ack3#356]
I was recently unable to install ack.  The command

```
curl https://beyondgrep.com/ack-v3.5.0 > ~/bin/ack && chmod 0755 ~/bin/ack
```

gives

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```

It seems like this problem should affect a lot of people, so perhaps I am doing something wrong.  But I have installed ack without problems this way in the past.

**Comment by Kriechi** [comment]
It's not just you - I have the same issues - came here to report it - found that it's already reported. 👍

**Comment by petdance** [comment]
Fixed. Thanks. Now I need to figure out why I didn't see the quarterly reminder email from letsencrypt. :-(
