### ISSUE TITLE
Missing extension for R language

### ISSUE THREAD

**Issue by kieran-mace** [beyondgrep/ack3#358]
https://github.com/beyondgrep/ack3/blob/428a79e314ea0534b39ddad45e53acf2aeeccbf8/garage/ack-v3.1.2#L3457

R and the R ecosystem supports two file types: .R and .Rmd

It would be great to support this by default. the necessary code change would be: 

from 

`--type-add=rr:ext:R`

to 

`--type-add=rr:ext:R,Rmd`

**Comment by Skytherian** [comment]
[This](https://cran.r-project.org/doc/manuals/R-exts.html) explains .R extensions.

For Rmarkdown(.Rmd) -> https://r4ds.had.co.nz/r-markdown.html#r-markdown-basics

**Comment by petdance** [comment]
Done in 0c9ee35
