### ISSUE TITLE
Support ".ps1" PowerShell file type

### ISSUE THREAD

**Issue by thgossler** [beyondgrep/ack3#362]
Please add PowerShell .ps1 to the known file types.

**Comment by petdance** [comment]
Please point to the docs for it. Are there other extensions that might need to go with it? Are there any potential collisions with other files called .ps1 we should know about?

**Comment by thgossler** [comment]
PowerShell uses only the following defined extensions:

.ps1 => scripts (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scripts?view=powershell-7.2)

.psm1 => modules (https://learn.microsoft.com/en-us/powershell/scripting/developer/module/understanding-a-windows-powershell-module?view=powershell-7.2)

.psd1 => module manifest (https://learn.microsoft.com/en-us/powershell/scripting/developer/module/understanding-a-windows-powershell-module?view=powershell-7.2#module-manifests)

These extensions have no dependencies to other file types and should be unique as well.

**Comment by thgossler** [comment]
Thanks! Yes, I found the option to extend the config myself via .ackrc file or command line. This is great.

Still, it would be nice to have it supported out of the box.

Actually, I would expect .ps1 and .psm1 files to be searched (both contain relevant PS code), but not .psd1.

**Comment by petdance** [comment]
So have you been using the config aliases for a while? How long? With both ps1 and psm1 and not psd1?

> it would be nice to have it supported out of the box.

Understood. I'm basically asking you to be a beta tester for this change. Maybe you'll turn up some sort of problem.

**Comment by petdance** [comment]
Done at f18e96a
