### ISSUE TITLE
Missing release email for ack v3.7.0

### ISSUE THREAD

**Issue by rajiv** [beyondgrep/ack3#369]
[ack v3.7.0](https://github.com/beyondgrep/ack3/releases/tag/v3.7.0) was tagged on Feb 25, and [announced on twitter](https://twitter.com/BeyondGrep/status/1631022904245624835) on Mar 1. Please also send a release announcement email to the [ack-announce email list](https://groups.google.com/d/forum/ack-announce).

Thank you for the useful software!

**Comment by petdance** [comment]
Ooops, sorry about that.  Thanks for the reminder.
