### ISSUE TITLE
Improve speed by reduce stat syscall

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#44]
_From @kcwu on November 27, 2010 17:46_

This is idea to improve file search speed.

Currently, ack use File::Next to search files.
It will stat each entry inside directory, to determine it is file or directory.
After File::Next know the entry is normal file (via -f), it will callback to ack's file_filter.

If we assume directory name won't look like file, it is possible to speed up:
1. Check entry name first. If the name is recognized by ack, but isn't interested by this search, we can just ignore such entry.
2. Only test it's file/dir/link if the name is not recognized by ack.

However, it may accident ignore directories with name recognized by ack. So this feature may need a option to let user turn on/off.

_Copied from original issue: petdance/ack#149_

**Comment by petdance** [comment]
_From @kcwu on March 3, 2011 4:14_

By the way, linux's readdir(3) return "d_type" which specify a entry is directory or not. Thus save a lot of stat(2) calls.

Linux's find(1) takes this advantage and is much faster. I don't know how to apply this trick in perl though.

**Comment by petdance** [comment]
_From @hoelzro on August 28, 2013 21:7_

Migrated to ack2 queue.

**Comment by petdance** [comment]
This was done in v3.1.0 and v3.1.1.

**Comment by kcwu** [comment]
I can't find relevant commits in 3.1.0 and 3.1.1. Do you mean it is done earlier?

**Comment by petdance** [comment]
Sorry, I didn't explain enough in the Change log.  ack v3.1.1 uses File::Next 1.18, which is more economical with `stat()` calls.

I've updated the Changes file: cb7578e

**Comment by kcwu** [comment]
I see. The change is in File::Next https://github.com/petdance/file-next/commit/470900a56b635d0516a3af71370912e6e520a185.

Thanks
