### ISSUE TITLE
Make all of $opt_xxx be package variables in App::Ack

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack3#65]
Let's stop passing around `$opt` everywhere.  We have globals in `main`.  Move them to App::Ack so that App::Ack::File can see them easily.

**Comment by petdance** [comment]
This should be done as a last thing before going to 3.000.

**Comment by n1vux** [comment]
Does that major a 'last change' require extended Beta / RC testing?

**Comment by petdance** [comment]
I don't think so.  Really, I just don't want it to be something we do now, before we go to beta.

**Comment by petdance** [comment]
Starting a branch `globals` to work on this.

**Comment by petdance** [comment]
Don't do this until #122 is working.

**Comment by petdance** [comment]
I don't think this is worth doing.  I've whittled most things down to package variables in main::.
